fix

diff --git a/.github/workflows/update-shells.yml b/.github/workflows/update-shells.yml
--- a/.github/workflows/update-shells.yml
+++ b/.github/workflows/update-shells.yml
@@ -40,9 +40,13 @@ jobs:
             echo "No changes to commit for Sunny Valley."
           else
             git commit -m "Update Sunny Valley shells"
-            git pull --rebase origin workflow/update-shells/${{ github.run_id }} || { echo "Pull failed; possibly due to conflicts."; exit 1; }
-            git push origin workflow/update-shells/${{ github.run_id }}
           fi
+
+          if git ls-remote --exit-code --heads origin workflow/update-shells/${{ github.run_id }}; then
+            git pull --rebase origin workflow/update-shells/${{ github.run_id }} || { echo "Pull failed; possibly due to conflicts."; exit 1; }
+          fi
+
+          git push origin workflow/update-shells/${{ github.run_id }}
 
   multicrew-tank-combat:
     runs-on: ubuntu-latest
@@ -78,9 +82,13 @@ jobs:
             echo "No changes to commit for MTC."
           else
             git commit -m "Update MTC shells"
-            git pull --rebase origin workflow/update-shells/${{ github.run_id }} || { echo "Pull failed; possibly due to conflicts."; exit 1; }
-            git push origin workflow/update-shells/${{ github.run_id }}
           fi
+
+          if git ls-remote --exit-code --heads origin workflow/update-shells/${{ github.run_id }}; then
+            git pull --rebase origin workflow/update-shells/${{ github.run_id }} || { echo "Pull failed; possibly due to conflicts."; exit 1; }
+          fi
+
+          git push origin workflow/update-shells/${{ github.run_id }}
 
   finalize-git-changes:
     runs-on: ubuntu-latest
