a

diff --git a/.github/workflows/update-kdr-data.yml b/.github/workflows/update-kdr-data.yml
--- a/.github/workflows/update-kdr-data.yml
+++ b/.github/workflows/update-kdr-data.yml
@@ -69,10 +69,14 @@ jobs:
       - run: |
           git fetch --all
           if git branch -r | grep -q "origin/workflow/update-kdr-data/${{ github.run_id }}"; then
-            if ! git diff --quiet origin/workflow/update-kdr-data/${{ github.run_id }} -- ./data/kdr/vehiclesInLoadout.json; then
-              git checkout origin/workflow/update-kdr-data/${{ github.run_id }} -- ./data/kdr/vehiclesInLoadout.json
+            if ! git diff --quiet origin/workflow/update-kdr-data/${{ github.run_id }} -- ./data/kdr/**; then
+              git checkout origin/workflow/update-kdr-data/${{ github.run_id }} -- ./data/kdr/**
+              git add ./data/kdr/**
+              git commit -m "Update KDR data"
+              git pull --ff-only origin workflow/update-kdr-data/${{ github.run_id }} || echo "Pull failed; possibly due to conflicts."
+              git push origin workflow/update-kdr-data/${{ github.run_id }}
             else
-              echo "No changes detected in vehiclesInLoadout.json."
+              echo "No changes detected in data."
             fi
           else
             echo "Branch workflow/update-kdr-data/${{ github.run_id }} does not exist."
@@ -90,7 +94,9 @@ jobs:
             git checkout -b workflow/update-kdr-data/${{ github.run_id }}
             git add ./data/kdr/**
             git commit -m "Update KDR data"
-            git pull origin workflow/update-kdr-data/${{ github.run_id }} --rebase
+            if git branch -r | grep -q "origin/workflow/update-kdr-data/${{ github.run_id }}"; then
+              git pull origin workflow/update-kdr-data/${{ github.run_id }} --ff-only
+            fi
             git push origin workflow/update-kdr-data/${{ github.run_id }}
           else
             echo "No changes detected in data"
@@ -118,7 +124,7 @@ jobs:
                 git checkout origin/workflow/update-kdr-data/${{ github.run_id }} -- ./data/kdr/**
                 git add ./data/kdr/**
                 git commit -m "Update KDR data from workflow/update-kdr-data/${{ github.run_id }}"
-                git pull origin $branch --rebase
+                git pull origin $branch --ff-only
                 git push origin $branch
               else
                 echo "No changes to commit on $branch."
